name: py_entitymatching_dev
channels:
  - conda-forge
  - uwmagellan
  - defaults
dependencies:
    - setuptools
    - py_stringsimjoin
    - cloudpickle
    - pyparsing
    - scikit-learn >= 0.18
    - pyqt
    - py_stringmatching
    - pandas-profiling
#    - xgboost
