package:
  name: py_labeler
  version: "0.1.0"

source:
    git_url: ../


requirements:
  build:
    - python
    - setuptools
    - pandas
    - six
    - jinja2

  run:
    - python
    - setuptools
    - pandas
    - six
    - jinja2

test:
  # Python imports
  imports:
    - py_labeler

  # commands:
    # You can putls test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://sites.google.com/site/anhaidgroup/projects/magellan/py_labeler
  license: BSD License
  summary: 'Python library for entity matching.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
